<Project>
    <PropertyGroup>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="ScriptHookVDotNetCore">
            <HintPath>..\..\..\..\..\ScriptHookVDotNetCore\bin\ScriptHookVDotNetCore.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="RageCoop.Client.Scripting">
            <HintPath>..\..\..\..\..\RAGECOOP-V\bin\Release\Client\Scripts\RageCoop.Client.Scripting.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="RageCoop.Core">
            <HintPath>..\..\..\..\..\RAGECOOP-V\bin\Release\Core\RageCoop.Core.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>
</Project>
