<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="RageCoop.Core">
			<HintPath>..\..\..\..\..\RAGECOOP-V\bin\Release\Core\RageCoop.Core.dll</HintPath>
		</Reference>
		<Reference Include="RageCoop.Server">
			<HintPath>..\..\..\..\..\RAGECOOP-V\bin\Release\Server\RageCoop.Server.dll</HintPath>
		</Reference>
		<Reference Include="ScriptHookVDotNetCore">
			<HintPath>..\..\..\..\..\ScriptHookVDotNetCore\bin\Release\ScriptHookVDotNetCore.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
